#!/bin/bash
set -e

source utils

EXIT=0

if [ "$APP_MODE" == "run" ]; then

  COUNTER_APP=$(MYSQL_QUERY \
  "SELECT COUNT(*)
  FROM $APP_TABLE
  WHERE app_name='$APP_NAME'
  AND app_uid='$APP_UID'
  AND app_version='$APP_VERSION'
  AND app_secret='$APP_SECRET'
  ;")

  if [ "$COUNTER_APP" -ne 1 ]; then

    EXIT=1

  fi

fi

echo $EXIT
