#!/bin/bash
set -e

source utils

if [ "$1" = 'supervisord' ]; then

  echo '       d8888 8888888b.  888b    888                                                 '
  echo '      d88888 888  "Y88b 8888b   888                                                 '
  echo '     d88P888 888    888 88888b  888                                                 '
  echo '    d88P 888 888    888 888Y88b 888                                                 '
  echo '   d88P  888 888    888 888 Y88b888                                                 '
  echo '  d88P   888 888    888 888  Y88888                                                 '
  echo ' d8888888888 888  .d88P 888   Y8888                                                 '
  echo 'd88P     888 8888888P"  888    Y888                                                 '
  echo '                                                                                    '
  echo '888b     d888        d8888  .d8888b.  8888888888 888b    888 88888888888 .d88888b.  '
  echo '8888b   d8888       d88888 d88P  Y88b 888        8888b   888     888    d88P" "Y88b '
  echo '88888b.d88888      d88P888 888    888 888        88888b  888     888    888     888 '
  echo '888Y88888P888     d88P 888 888        8888888    888Y88b 888     888    888     888 '
  echo '888 Y888P 888    d88P  888 888  88888 888        888 Y88b888     888    888     888 '
  echo '888  Y8P  888   d88P   888 888    888 888        888  Y88888     888    888     888 '
  echo '888   "   888  d8888888888 Y88b  d88P 888        888   Y8888     888    Y88b. .d88P '
  echo '888       888 d88P     888  "Y8888P88 8888888888 888    Y888     888     "Y88888P"  '
  echo ''

  for entrypoint in $(cat "/usr/bin/docker-entrypoint.list"); do

    if [ "${entrypoint:0:1}" != "#" ] && [ -f "/usr/bin/$entrypoint" ]; then

      echo "Execute $entrypoint"

      . $entrypoint "$@"

    fi

  done

fi

exec "$@"
